[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = ['npm run build', 'node scripts/copy-sharp.js']

[start]
cmd = 'node .next/standalone/server.js'
