[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-10_x']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = [
  'npm run build',
  'cp -r node_modules/sharp .next/standalone/node_modules/ || true'
]

[start]
cmd = 'node .next/standalone/server.js'

[variables]
NODE_ENV = 'production'
NEXT_SHARP_PATH = '/tmp/node_modules/sharp'